import { NextResponse } from "next/server";
import { google } from "googleapis";
import { randomUUID } from "node:crypto";

/**
 * Transaction API (Google Sheets as the single source of truth)
 *
 * Expected sheet columns (A-E):
 * - Id
 * - Tanggal
 * - Kiteria
 * - Pengeluaran
 * - Note
 *
 * Routes:
 * - GET    /api/transaction            List with filters + pagination + summary
 * - POST   /api/transaction            Append one/many rows (ID generated by API)
 * - PATCH  /api/transaction            Update by id (id is immutable)
 * - DELETE /api/transaction?id=TX-...  Delete by id (header row is protected)
 *
 * Auth:
 * Uses a Google Service Account via environment variables:
 * - GOOGLE_CLIENT_EMAIL
 * - GOOGLE_PRIVATE_KEY (stored with \n escapes inside .env)
 * - GOOGLE_SHEET_ID
 * - GOOGLE_SHEET_TITLE (tab name, e.g. 2026)
 */
type TransactionRow = {
  id: string;
  tanggal: string;
  kriteria: string;
  pengeluaran: string;
  note: string;
  pengeluaranNumber: number | null;
};

export const runtime = "nodejs";

function normalizeHeader(value: string) {
  return value.trim().toLowerCase();
}

function parseDateLoose(input: string): Date | null {
  const raw = input.trim();
  if (!raw) return null;

  // Prefer dd/mm/yyyy (or dd-mm-yyyy) to avoid Date() treating it as mm/dd/yyyy.
  const m1 = raw.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})$/);
  if (m1) {
    const day = Number(m1[1]);
    const month = Number(m1[2]);
    const year = Number(m1[3]);
    const d = new Date(year, month - 1, day);
    return Number.isNaN(d.getTime()) ? null : d;
  }

  const iso = new Date(raw);
  if (!Number.isNaN(iso.getTime())) return iso;

  return null;
}

function monthKey(date: Date) {
  const y = date.getFullYear();
  const m = date.getMonth() + 1;
  return `${y}-${String(m).padStart(2, "0")}`;
}

function shiftMonth(key: string, deltaMonths: number) {
  const [yStr, mStr] = key.split("-");
  const y = Number(yStr);
  const m = Number(mStr);
  const base = y * 12 + (m - 1);
  const shifted = base + deltaMonths;
  const newY = Math.floor(shifted / 12);
  const newM = (shifted % 12) + 1;
  return `${newY}-${String(newM).padStart(2, "0")}`;
}

function parseMoneyToNumber(input: string): number | null {
  const cleaned = input
    .trim()
    .replace(/\s/g, "")
    .replace(/[^0-9,.\-]/g, "");

  if (!cleaned) return null;

  let normalized = cleaned;
  if (cleaned.includes(",")) {
    normalized = cleaned.replace(/\./g, "").replace(",", ".");
  } else {
    normalized = cleaned.replace(/\./g, "");
  }

  const num = Number(normalized);
  return Number.isFinite(num) ? num : null;
}

function getServiceAccountCredentials() {
  const clientEmail = process.env.GOOGLE_CLIENT_EMAIL ?? "";
  const privateKeyRaw = process.env.GOOGLE_PRIVATE_KEY ?? "";
  const privateKey = privateKeyRaw.replace(/\\n/g, "\n");
  return { clientEmail, privateKey };
}

async function getSheetsClient() {
  const { clientEmail, privateKey } = getServiceAccountCredentials();
  if (!clientEmail || !privateKey) return null;

  const auth = new google.auth.JWT({
    email: clientEmail,
    key: privateKey,
    scopes: ["https://www.googleapis.com/auth/spreadsheets"],
  });

  await auth.authorize();
  return google.sheets({ version: "v4", auth });
}

function findColumnIndex(headers: string[], targets: string[]) {
  for (const t of targets) {
    const idx = headers.indexOf(t);
    if (idx !== -1) return idx;
  }
  return -1;
}

function mapRowsToTransactions(values: string[][]) {
  const headerRow = (values[0] ?? []).map((h) =>
    normalizeHeader(String(h ?? "")),
  );
  const idxId = findColumnIndex(headerRow, ["id"]);
  const idxTanggal = findColumnIndex(headerRow, ["tanggal", "date"]);
  const idxKriteria = findColumnIndex(headerRow, [
    "kiteria",
    "kriteria",
    "kategori",
    "category",
  ]);
  const idxPengeluaran = findColumnIndex(headerRow, ["pengeluaran", "amount"]);
  const idxNote = findColumnIndex(headerRow, ["note", "catatan"]);

  if (
    idxId === -1 ||
    idxTanggal === -1 ||
    idxKriteria === -1 ||
    idxPengeluaran === -1 ||
    idxNote === -1
  ) {
    return {
      ok: false as const,
      error: {
        message:
          'Header data tidak sesuai. Pastikan ada kolom: "Id", "Tanggal", "Kiteria", "Pengeluaran", "Note".',
        detectedHeaders: headerRow,
      },
    };
  }

  const data: TransactionRow[] = values.slice(1).map((row) => {
    const id = String(row[idxId] ?? "").trim();
    const tanggal = String(row[idxTanggal] ?? "").trim();
    const kriteria = String(row[idxKriteria] ?? "").trim();
    const pengeluaran = String(row[idxPengeluaran] ?? "").trim();
    const note = String(row[idxNote] ?? "").trim();

    return {
      id,
      tanggal,
      kriteria,
      pengeluaran,
      note,
      pengeluaranNumber: parseMoneyToNumber(pengeluaran),
    };
  });

  return { ok: true as const, data, headerRow };
}

export async function GET(req: Request) {
  const spreadsheetId = process.env.GOOGLE_SHEET_ID;
  const sheetTitle = process.env.GOOGLE_SHEET_TITLE ?? "Sheet1";
  const range = process.env.GOOGLE_SHEET_RANGE ?? `${sheetTitle}!A:E`;

  if (!spreadsheetId) {
    return NextResponse.json(
      { message: "GOOGLE_SHEET_ID belum di-set.", data: [] },
      { status: 500 },
    );
  }

  const sheets = await getSheetsClient();
  if (!sheets) {
    return NextResponse.json(
      {
        message:
          "Konfigurasi service account belum lengkap. Pastikan GOOGLE_CLIENT_EMAIL dan GOOGLE_PRIVATE_KEY terisi.",
        data: [],
      },
      { status: 500 },
    );
  }

  let values: string[][] = [];
  try {
    const resp = await sheets.spreadsheets.values.get({
      spreadsheetId,
      range,
    });
    values = (resp.data.values as string[][]) ?? [];
  } catch {
    return NextResponse.json(
      { message: "Gagal fetch data dari Google Sheets.", data: [] },
      { status: 502 },
    );
  }

  if (!values.length) {
    return NextResponse.json(
      { message: "Sheet kosong / data tidak ditemukan.", count: 0, data: [] },
      { status: 200 },
    );
  }

  const mapped = mapRowsToTransactions(values);
  if (!mapped.ok) {
    return NextResponse.json(
      {
        message: mapped.error.message,
        detectedHeaders: mapped.error.detectedHeaders,
        data: [],
      },
      { status: 422 },
    );
  }

  const requestUrl = new URL(req.url);
  const q = requestUrl.searchParams;

  // Server-side filters + pagination so the UI can page 100 rows at a time.
  const page = Math.max(1, Number(q.get("page") ?? "1") || 1);
  const limitRaw = Number(q.get("limit") ?? "100") || 100;
  const limit = Math.max(1, Math.min(500, limitRaw));

  const id = q.get("id");
  const category = q.get("category") ?? q.get("kiteria") ?? q.get("kriteria");
  const from = q.get("from") ?? q.get("start");
  const to = q.get("to") ?? q.get("end");
  const search = q.get("search");

  let rows = mapped.data;
  const categories = Array.from(
    new Set(rows.map((r) => r.kriteria).filter((v) => v.trim().length > 0)),
  ).sort((a, b) => a.localeCompare(b));
  const years = Array.from(
    new Set(
      rows
        .map((r) => parseDateLoose(r.tanggal))
        .filter((d): d is Date => d !== null)
        .map((d) => d.getFullYear()),
    ),
  ).sort((a, b) => a - b);

  if (id) rows = rows.filter((r) => r.id === id);
  if (category && category !== "All")
    rows = rows.filter((r) => r.kriteria === category);
  if (search) {
    const s = search.toLowerCase();
    rows = rows.filter(
      (r) =>
        r.id.toLowerCase().includes(s) ||
        r.tanggal.toLowerCase().includes(s) ||
        r.kriteria.toLowerCase().includes(s) ||
        r.pengeluaran.toLowerCase().includes(s) ||
        r.note.toLowerCase().includes(s),
    );
  }

  const fromDate = from ? parseDateLoose(from) : null;
  const toDate = to ? parseDateLoose(to) : null;
  if (fromDate || toDate) {
    const start = fromDate
      ? new Date(
          fromDate.getFullYear(),
          fromDate.getMonth(),
          fromDate.getDate(),
        )
      : null;
    const end = toDate
      ? new Date(
          toDate.getFullYear(),
          toDate.getMonth(),
          toDate.getDate(),
          23,
          59,
          59,
          999,
        )
      : null;

    rows = rows.filter((r) => {
      const d = parseDateLoose(r.tanggal);
      if (!d) return false;
      if (start && d < start) return false;
      if (end && d > end) return false;
      return true;
    });
  }

  const totalCount = rows.length;

  const totalVolume = rows.reduce(
    (acc, r) => acc + Math.abs(r.pengeluaranNumber ?? 0),
    0,
  );

  const monthlyTotals = new Map<string, number>();
  for (const r of rows) {
    const d = parseDateLoose(r.tanggal);
    if (!d) continue;
    const key = monthKey(d);
    monthlyTotals.set(
      key,
      (monthlyTotals.get(key) ?? 0) + Math.abs(r.pengeluaranNumber ?? 0),
    );
  }

  const monthKeys = Array.from(monthlyTotals.keys()).sort();
  const currentKey = monthKeys.length ? monthKeys[monthKeys.length - 1] : null;
  const previousKey = currentKey ? shiftMonth(currentKey, -1) : null;
  const currentTotal = currentKey ? (monthlyTotals.get(currentKey) ?? 0) : 0;
  const previousTotal = previousKey ? (monthlyTotals.get(previousKey) ?? 0) : 0;

  const percentChange =
    previousTotal > 0
      ? Math.round(
          ((currentTotal - previousTotal) / previousTotal) * 100 * 10,
        ) / 10
      : null;
  const trend =
    percentChange === null
      ? "flat"
      : percentChange > 0
        ? "up"
        : percentChange < 0
          ? "down"
          : "flat";

  const offset = (page - 1) * limit;
  const data = rows.slice(offset, offset + limit);

  return NextResponse.json(
    {
      message: "Berhasil mengambil data transaksi dari Google Sheets.",
      totalCount,
      page,
      limit,
      count: data.length,
      categories,
      years,
      summary: {
        totalVolume,
        percentChange,
        trend,
        validatedEntries: totalCount,
      },
      data,
    },
    { status: 200 },
  );
}

export async function POST(req: Request) {
  const spreadsheetId = process.env.GOOGLE_SHEET_ID;
  const sheetTitle = process.env.GOOGLE_SHEET_TITLE ?? "Sheet1";
  const range = process.env.GOOGLE_SHEET_RANGE ?? `${sheetTitle}!A:E`;

  if (!spreadsheetId) {
    return NextResponse.json(
      { message: "GOOGLE_SHEET_ID belum di-set." },
      { status: 500 },
    );
  }

  const sheets = await getSheetsClient();
  if (!sheets) {
    return NextResponse.json(
      {
        message:
          "Konfigurasi service account belum lengkap. Pastikan GOOGLE_CLIENT_EMAIL dan GOOGLE_PRIVATE_KEY terisi.",
      },
      { status: 500 },
    );
  }

  let payload: unknown = null;
  try {
    payload = await req.json();
  } catch {
    payload = null;
  }

  let items: Array<{
    tanggal: string;
    kriteria: string;
    pengeluaran: string;
    note: string;
  }> = [];

  if (payload && typeof payload === "object") {
    if (
      "items" in payload &&
      Array.isArray((payload as { items?: unknown }).items)
    ) {
      items = (payload as { items: typeof items }).items;
    } else {
      const single = payload as Partial<(typeof items)[number]>;
      if (
        typeof single.tanggal === "string" ||
        typeof single.kriteria === "string" ||
        typeof single.pengeluaran === "string" ||
        typeof single.note === "string"
      ) {
        items = [
          {
            tanggal: String(single.tanggal ?? ""),
            kriteria: String(single.kriteria ?? ""),
            pengeluaran: String(single.pengeluaran ?? ""),
            note: String(single.note ?? ""),
          },
        ];
      }
    }
  }

  if (!items.length) {
    return NextResponse.json(
      { message: "Body wajib berisi items." },
      { status: 400 },
    );
  }

  let values: string[][] = [];
  try {
    const resp = await sheets.spreadsheets.values.get({
      spreadsheetId,
      range,
    });
    values = (resp.data.values as string[][]) ?? [];
  } catch {
    return NextResponse.json(
      { message: "Gagal fetch data dari Google Sheets." },
      { status: 502 },
    );
  }

  if (!values.length) {
    return NextResponse.json(
      { message: "Header sheet tidak ditemukan." },
      { status: 422 },
    );
  }

  const mapped = mapRowsToTransactions(values);
  if (!mapped.ok) {
    return NextResponse.json(
      {
        message: mapped.error.message,
        detectedHeaders: mapped.error.detectedHeaders,
      },
      { status: 422 },
    );
  }

  const headerRow = (values[0] ?? []).map((h) =>
    normalizeHeader(String(h ?? "")),
  );
  const idxId = findColumnIndex(headerRow, ["id"]);
  const idxTanggal = findColumnIndex(headerRow, ["tanggal", "date"]);
  const idxKriteria = findColumnIndex(headerRow, [
    "kiteria",
    "kriteria",
    "kategori",
    "category",
  ]);
  const idxPengeluaran = findColumnIndex(headerRow, ["pengeluaran", "amount"]);
  const idxNote = findColumnIndex(headerRow, ["note", "catatan"]);

  const indices = [idxId, idxTanggal, idxKriteria, idxPengeluaran, idxNote];
  if (indices.some((idx) => idx < 0 || idx > 4)) {
    return NextResponse.json(
      {
        message: "Urutan kolom sheet tidak sesuai (harus berada di A-E).",
        detectedHeaders: headerRow,
      },
      { status: 422 },
    );
  }

  const existingIds = new Set(mapped.data.map((r) => r.id));
  const created: TransactionRow[] = [];
  const rowsToAppend: string[][] = [];

  for (const item of items) {
    const tanggal = String(item.tanggal ?? "").trim();
    const kriteria = String(item.kriteria ?? "").trim();
    const pengeluaran = String(item.pengeluaran ?? "").trim();
    const note = String(item.note ?? "").trim();

    if (!tanggal || !kriteria || !pengeluaran) {
      return NextResponse.json(
        { message: "Field tanggal, kriteria, dan pengeluaran wajib diisi." },
        { status: 400 },
      );
    }

    let id = "";
    for (let attempt = 0; attempt < 5; attempt++) {
      const candidate =
        `TX-${Date.now()}-${randomUUID().slice(0, 6)}`.toUpperCase();
      if (!existingIds.has(candidate)) {
        id = candidate;
        existingIds.add(candidate);
        break;
      }
    }

    if (!id) {
      return NextResponse.json(
        { message: "Gagal generate id transaksi." },
        { status: 500 },
      );
    }

    const row = new Array<string>(5).fill("");
    row[idxId] = id;
    row[idxTanggal] = tanggal;
    row[idxKriteria] = kriteria;
    row[idxPengeluaran] = pengeluaran;
    row[idxNote] = note;

    rowsToAppend.push(row);
    created.push({
      id,
      tanggal,
      kriteria,
      pengeluaran,
      note,
      pengeluaranNumber: parseMoneyToNumber(pengeluaran),
    });
  }

  try {
    await sheets.spreadsheets.values.append({
      spreadsheetId,
      range: `${sheetTitle}!A:E`,
      valueInputOption: "RAW",
      insertDataOption: "INSERT_ROWS",
      requestBody: {
        values: rowsToAppend,
      },
    });
  } catch {
    return NextResponse.json(
      { message: "Gagal menambahkan data ke Google Sheets." },
      { status: 502 },
    );
  }

  return NextResponse.json(
    {
      message: "Berhasil menambahkan transaksi.",
      count: created.length,
      data: created,
    },
    { status: 201 },
  );
}

export async function PATCH(req: Request) {
  const spreadsheetId = process.env.GOOGLE_SHEET_ID;
  const sheetTitle = process.env.GOOGLE_SHEET_TITLE ?? "Sheet1";
  const range = process.env.GOOGLE_SHEET_RANGE ?? `${sheetTitle}!A:E`;

  if (!spreadsheetId) {
    return NextResponse.json(
      { message: "GOOGLE_SHEET_ID belum di-set." },
      { status: 500 },
    );
  }

  const sheets = await getSheetsClient();
  if (!sheets) {
    return NextResponse.json(
      {
        message:
          "Konfigurasi service account belum lengkap. Pastikan GOOGLE_CLIENT_EMAIL dan GOOGLE_PRIVATE_KEY terisi.",
      },
      { status: 500 },
    );
  }

  let payload: Partial<TransactionRow> & { id?: string } = {};
  try {
    payload = (await req.json()) as Partial<TransactionRow> & { id?: string };
  } catch {
    payload = {};
  }

  const targetId = (payload.id ?? "").trim();
  if (!targetId) {
    return NextResponse.json(
      { message: "Field id wajib diisi untuk update." },
      { status: 400 },
    );
  }

  let values: string[][] = [];
  try {
    const resp = await sheets.spreadsheets.values.get({
      spreadsheetId,
      range,
    });
    values = (resp.data.values as string[][]) ?? [];
  } catch {
    return NextResponse.json(
      { message: "Gagal fetch data dari Google Sheets." },
      { status: 502 },
    );
  }

  if (!values.length) {
    return NextResponse.json(
      { message: "Sheet kosong / data tidak ditemukan." },
      { status: 404 },
    );
  }

  const mapped = mapRowsToTransactions(values);
  if (!mapped.ok) {
    return NextResponse.json(
      {
        message: mapped.error.message,
        detectedHeaders: mapped.error.detectedHeaders,
      },
      { status: 422 },
    );
  }

  const headerRow = (values[0] ?? []).map((h) =>
    normalizeHeader(String(h ?? "")),
  );
  const idxId = findColumnIndex(headerRow, ["id"]);
  const idxTanggal = findColumnIndex(headerRow, ["tanggal", "date"]);
  const idxKriteria = findColumnIndex(headerRow, [
    "kiteria",
    "kriteria",
    "kategori",
    "category",
  ]);
  const idxPengeluaran = findColumnIndex(headerRow, ["pengeluaran", "amount"]);
  const idxNote = findColumnIndex(headerRow, ["note", "catatan"]);

  const rowIndex = values.findIndex(
    (row, i) => i !== 0 && String(row[idxId] ?? "").trim() === targetId,
  );
  if (rowIndex === -1) {
    return NextResponse.json(
      { message: `Data dengan id ${targetId} tidak ditemukan.` },
      { status: 404 },
    );
  }

  const existing = values[rowIndex] ?? [];
  const updatedRow = [...existing];

  updatedRow[idxId] = targetId;
  if (payload.tanggal !== undefined) updatedRow[idxTanggal] = payload.tanggal;
  if (payload.kriteria !== undefined)
    updatedRow[idxKriteria] = payload.kriteria;
  if (payload.pengeluaran !== undefined)
    updatedRow[idxPengeluaran] = payload.pengeluaran;
  if (payload.note !== undefined) updatedRow[idxNote] = payload.note;

  const a1Row = rowIndex + 1;
  const updateRange = `${sheetTitle}!A${a1Row}:E${a1Row}`;

  try {
    await sheets.spreadsheets.values.update({
      spreadsheetId,
      range: updateRange,
      valueInputOption: "RAW",
      requestBody: {
        values: [updatedRow.slice(0, 5)],
      },
    });
  } catch {
    return NextResponse.json(
      { message: "Gagal update data ke Google Sheets." },
      { status: 502 },
    );
  }

  const updatedMapped = mapRowsToTransactions([
    values[0],
    updatedRow.slice(0, 5),
  ]);
  const updated = updatedMapped.ok ? updatedMapped.data[0] : null;

  return NextResponse.json(
    { message: "Berhasil update transaksi.", data: updated },
    { status: 200 },
  );
}

export async function DELETE(req: Request) {
  const spreadsheetId = process.env.GOOGLE_SHEET_ID;
  const sheetTitle = process.env.GOOGLE_SHEET_TITLE ?? "Sheet1";
  const range = process.env.GOOGLE_SHEET_RANGE ?? `${sheetTitle}!A:E`;

  if (!spreadsheetId) {
    return NextResponse.json(
      { message: "GOOGLE_SHEET_ID belum di-set." },
      { status: 500 },
    );
  }

  const sheets = await getSheetsClient();
  if (!sheets) {
    return NextResponse.json(
      {
        message:
          "Konfigurasi service account belum lengkap. Pastikan GOOGLE_CLIENT_EMAIL dan GOOGLE_PRIVATE_KEY terisi.",
      },
      { status: 500 },
    );
  }

  const url = new URL(req.url);
  const targetId = (url.searchParams.get("id") ?? "").trim();
  if (!targetId) {
    return NextResponse.json(
      {
        message:
          "Query param id wajib diisi untuk delete. Contoh: /api/transaction?id=123",
      },
      { status: 400 },
    );
  }

  let values: string[][] = [];
  try {
    const resp = await sheets.spreadsheets.values.get({
      spreadsheetId,
      range,
    });
    values = (resp.data.values as string[][]) ?? [];
  } catch {
    return NextResponse.json(
      { message: "Gagal fetch data dari Google Sheets." },
      { status: 502 },
    );
  }

  if (!values.length) {
    return NextResponse.json(
      { message: "Sheet kosong / data tidak ditemukan." },
      { status: 404 },
    );
  }

  const headerRow = (values[0] ?? []).map((h) =>
    normalizeHeader(String(h ?? "")),
  );
  const idxId = findColumnIndex(headerRow, ["id"]);
  if (idxId === -1) {
    return NextResponse.json(
      {
        message: 'Header data tidak sesuai. Kolom "Id" tidak ditemukan.',
        detectedHeaders: headerRow,
      },
      { status: 422 },
    );
  }

  const rowIndex = values.findIndex(
    (row, i) => i !== 0 && String(row[idxId] ?? "").trim() === targetId,
  );
  if (rowIndex === -1) {
    return NextResponse.json(
      { message: `Data dengan id ${targetId} tidak ditemukan.` },
      { status: 404 },
    );
  }

  let sheetNumericId: number | null = null;
  try {
    const meta = await sheets.spreadsheets.get({ spreadsheetId });
    const found = meta.data.sheets?.find(
      (s) => s.properties?.title === sheetTitle,
    );
    sheetNumericId = found?.properties?.sheetId ?? null;
  } catch {
    sheetNumericId = null;
  }

  if (sheetNumericId === null) {
    return NextResponse.json(
      { message: "Gagal mendapatkan sheetId untuk operasi delete." },
      { status: 502 },
    );
  }

  const startIndex = rowIndex;
  const endIndex = rowIndex + 1;

  if (startIndex <= 0) {
    return NextResponse.json(
      { message: "Tidak boleh menghapus header row." },
      { status: 400 },
    );
  }

  try {
    await sheets.spreadsheets.batchUpdate({
      spreadsheetId,
      requestBody: {
        requests: [
          {
            deleteDimension: {
              range: {
                sheetId: sheetNumericId,
                dimension: "ROWS",
                startIndex,
                endIndex,
              },
            },
          },
        ],
      },
    });
  } catch {
    return NextResponse.json(
      { message: "Gagal delete data dari Google Sheets." },
      { status: 502 },
    );
  }

  return NextResponse.json(
    { message: "Berhasil menghapus transaksi.", id: targetId },
    { status: 200 },
  );
}
